# Feature: owasp-auth-modules-hardening, Property 2: Same-object decisions are identity-based
"""
Property-Based Tests for the authorization-baseline identity comparison.

**Feature: owasp-auth-modules-hardening, Property 2: Same-object decisions are
identity-based**

Property 2 (from design.md):
    ``responses_identify_same_object(r1, r2)`` reports "same" (returns
    ``same=True``) IFF both response bodies expose a recognized
    Identifying_Field with an EQUAL value, and NEVER based on size/word
    similarity.

These tests drive the real ``responses_identify_same_object`` /
``extract_identifying_fields`` helpers in ``utils.authz_baseline`` against
``Response`` objects carrying JSON bodies generated by Hypothesis. No network
or mocking is involved -- responses are constructed directly.

Requirements covered: 2.1, 2.2, 2.4, 24.x.
"""

import json

import pytest
from hypothesis import given, settings, strategies as st

from utils.authz_baseline import (
    IDENTIFYING_FIELD_NAMES,
    extract_identifying_fields,
    responses_identify_same_object,
)
from utils.http_client import Response


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def make_response(body, status_code=200, url="https://api.example.com/object/1",
                  method="GET"):
    """Build a Response carrying ``body``.

    ``body`` may be a Python object (serialized to JSON) or a raw string (used
    verbatim, e.g. to model a non-JSON body).
    """
    if isinstance(body, str):
        text = body
    else:
        text = json.dumps(body)
    content = text.encode("utf-8")
    return Response(
        status_code=status_code,
        headers={"content-type": "application/json"},
        content=content,
        text=text,
        url=url,
        elapsed=0.01,
        request_method=method,
    )


# Canonical lowercase recognized field names.
_RECOGNIZED_LOWER = sorted({name.lower() for name in IDENTIFYING_FIELD_NAMES})

# Scalar identity values: ints, non-empty text, and booleans. Kept simple and
# JSON-serializable. Booleans are included because the implementation treats
# them as distinct from ints.
identity_values = st.one_of(
    st.integers(min_value=-(10 ** 6), max_value=10 ** 6),
    st.text(min_size=1, max_size=20),
    st.booleans(),
)

# Strategy for a recognized field name (using its original spelling so casing
# is exercised too).
recognized_field_names = st.sampled_from(IDENTIFYING_FIELD_NAMES)

# Non-recognized field names: any key that is NOT a recognized identifying
# field (case-insensitively).
non_recognized_field_names = st.text(min_size=1, max_size=12).filter(
    lambda k: k.lower() not in _RECOGNIZED_LOWER
)


def _scalar_equal(a, b):
    """Mirror of the implementation's scalar equality (bool != int)."""
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    return a == b


# ---------------------------------------------------------------------------
# Property 2.1: shared recognized field with EQUAL value -> same=True
# ---------------------------------------------------------------------------


@settings(max_examples=200)
@given(
    field_name=recognized_field_names,
    value=identity_values,
    extra1=st.dictionaries(non_recognized_field_names, st.integers(), max_size=3),
    extra2=st.dictionaries(non_recognized_field_names, st.integers(), max_size=3),
)
def test_shared_equal_identifying_field_is_same(field_name, value, extra1, extra2):
    """When both bodies expose a recognized field with an EQUAL value, the
    responses identify the same object and the returned field_name/value
    correspond to a real matching field.

    **Validates: Requirements 2.1, 2.2**
    """
    body1 = {**extra1, field_name: value}
    body2 = {**extra2, field_name: value}

    same, name, returned_value = responses_identify_same_object(
        make_response(body1), make_response(body2)
    )

    assert same is True
    assert name == field_name.lower()
    # The returned (name, value) must be a genuine match across both bodies.
    fields1 = extract_identifying_fields(make_response(body1))
    fields2 = extract_identifying_fields(make_response(body2))
    assert name in fields1 and name in fields2
    assert _scalar_equal(fields1[name], returned_value)
    assert _scalar_equal(fields2[name], returned_value)


# ---------------------------------------------------------------------------
# Property 2.2: recognized fields present but NO shared equal value -> same=False
# ---------------------------------------------------------------------------


@settings(max_examples=200)
@given(
    field_name=recognized_field_names,
    value_a=identity_values,
    value_b=identity_values,
)
def test_recognized_fields_without_equal_value_is_not_same(field_name, value_a, value_b):
    """When both bodies expose recognized identifying fields but no shared field
    holds an equal value, the responses are NOT identified as the same object.

    **Validates: Requirements 2.2, 2.4**
    """
    # Constrain to the case where the two values are genuinely unequal.
    if _scalar_equal(value_a, value_b):
        return

    body1 = {field_name: value_a}
    body2 = {field_name: value_b}

    same, name, returned_value = responses_identify_same_object(
        make_response(body1), make_response(body2)
    )

    assert same is False
    assert name is None
    assert returned_value is None


@settings(max_examples=200)
@given(
    field_a=recognized_field_names,
    field_b=recognized_field_names,
    value_a=identity_values,
    value_b=identity_values,
)
def test_disjoint_recognized_fields_is_not_same(field_a, field_b, value_a, value_b):
    """When each body exposes a *different* recognized field (no field in
    common), there is no shared equal value, so same=False.

    **Validates: Requirements 2.2, 2.4**
    """
    # Require the canonical field names to differ so the bodies share no field.
    if field_a.lower() == field_b.lower():
        return

    body1 = {field_a: value_a}
    body2 = {field_b: value_b}

    same, name, returned_value = responses_identify_same_object(
        make_response(body1), make_response(body2)
    )

    assert same is False
    assert name is None
    assert returned_value is None


# ---------------------------------------------------------------------------
# Property 2.3: no recognized identifying field -> (False, None, None)
# ---------------------------------------------------------------------------


@settings(max_examples=200)
@given(
    other_fields=st.dictionaries(non_recognized_field_names, st.integers(), max_size=4),
    field_name=recognized_field_names,
    value=identity_values,
)
def test_no_recognized_field_in_one_response_is_not_same(other_fields, field_name, value):
    """When one response exposes no recognized identifying field (JSON without
    recognized keys), the pair is never identified as the same object, even when
    the other response does expose a recognized field.

    **Validates: Requirements 2.4**
    """
    body_with_fields = {field_name: value}
    body_without = dict(other_fields)  # only non-recognized keys (possibly empty)

    same, name, returned_value = responses_identify_same_object(
        make_response(body_with_fields), make_response(body_without)
    )

    assert same is False
    assert name is None
    assert returned_value is None


@settings(max_examples=200)
@given(
    text_body=st.text(max_size=40),
    field_name=recognized_field_names,
    value=identity_values,
)
def test_non_json_body_is_not_same(text_body, field_name, value):
    """A non-JSON (unparseable) body exposes no identifying field, so it can
    never be the same object as another response. Degrades gracefully without
    raising.

    **Validates: Requirements 2.1, 2.4**
    """
    json_response = make_response({field_name: value})
    text_response = make_response(text_body)

    # The text body might coincidentally be valid JSON that exposes a
    # recognized identifying field (e.g. '{"id": 5}' or '[{"id": 5}]'). We want
    # a genuine "no identifying field" case here, so skip any example whose body
    # the extractor recognizes. extract_identifying_fields must never raise.
    if extract_identifying_fields(text_response):
        return

    same, name, returned_value = responses_identify_same_object(
        json_response, text_response
    )

    assert same is False
    assert name is None
    assert returned_value is None


# ---------------------------------------------------------------------------
# Property 2.4: size/word-similarity independence
# ---------------------------------------------------------------------------


@settings(max_examples=200)
@given(
    field_name=recognized_field_names,
    value_a=st.integers(min_value=0, max_value=10 ** 9),
    value_b=st.integers(min_value=0, max_value=10 ** 9),
    padding=st.text(alphabet="abcdefghijklmnopqrstuvwxyz ", min_size=200, max_size=400),
)
def test_identical_large_bodies_differing_identity_are_not_same(
    field_name, value_a, value_b, padding
):
    """Two responses with IDENTICAL large bodies (same size, same words) except
    for the identifying-field value are NOT the same object. This proves the
    decision is identity-based, not size/word-similarity based.

    **Validates: Requirements 2.4, 24.x**
    """
    if value_a == value_b:
        value_b = value_a + 1

    # Both bodies share the same large filler content -> maximally similar in
    # size and words; only the identity value differs.
    body1 = {field_name: value_a, "description": padding, "notes": padding}
    body2 = {field_name: value_b, "description": padding, "notes": padding}

    r1 = make_response(body1)
    r2 = make_response(body2)

    same, name, returned_value = responses_identify_same_object(r1, r2)

    assert same is False
    assert name is None
    assert returned_value is None


@settings(max_examples=200)
@given(
    field_name=recognized_field_names,
    value=identity_values,
    padding=st.text(alphabet="abcdefghijklmnopqrstuvwxyz ", min_size=300, max_size=600),
)
def test_very_different_sizes_same_identity_are_same(field_name, value, padding):
    """Two responses with VERY different body sizes but the SAME
    identifying-field value ARE the same object. A size/similarity heuristic
    would reject these; an identity-based decision accepts them.

    **Validates: Requirements 2.4, 24.x**
    """
    # body1 is tiny; body2 is large with lots of extra filler content.
    body1 = {field_name: value}
    body2 = {field_name: value, "description": padding, "notes": padding, "more": padding}

    r1 = make_response(body1)
    r2 = make_response(body2)

    # Sanity check: the bodies really do differ substantially in size.
    assert abs(len(r1.content) - len(r2.content)) > 100

    same, name, returned_value = responses_identify_same_object(r1, r2)

    assert same is True
    assert name == field_name.lower()
    assert _scalar_equal(returned_value, value)


if __name__ == "__main__":
    pytest.main([__file__, "-q"])
