# Feature: owasp-auth-modules-hardening, Property 30: Typed payloads honor declared types, required fields, and enums
"""
Property-Based Test for typed-payload validity (Req 57.3).

**Feature: owasp-auth-modules-hardening, Property 30: Typed payloads honor
declared types, required fields, and enums**

Property 30 (from design.md):
    *For all* ``SpecOperation`` values, the body produced by
    ``build_typed_payload`` (and the values produced by ``build_typed_params``)
    contains every ``required`` field, assigns each field a value whose runtime
    type matches the field's declared JSON Schema ``type``, and — for every field
    declaring an ``enum`` — assigns a value drawn from that field's declared
    ``enum`` set; when a field declares an ``example``/``examples``, the chosen
    value is that example and is itself type/enum valid.

The test drives the real, pure builders in ``utils.typed_payload`` with
``SpecOperation`` values generated by Hypothesis. Each operation mixes
required/optional fields, every declared JSON Schema type, and enum/example
decorations across both the request body schema and the query/header
parameters. No network or mocking is involved.

Requirements covered: 57.3, 52.1, 52.2, 52.3.
"""

import pytest
from hypothesis import given, settings, strategies as st

from utils.spec_import import SpecOperation, SpecParameter
from utils.typed_payload import build_typed_payload, build_typed_params


# ---------------------------------------------------------------------------
# Declared JSON Schema types and per-type value generators. Values placed in an
# ``enum`` or used as an ``example`` are drawn from the matching type generator
# so they are, by construction, type-consistent with the declared ``type`` —
# exactly the contract a well-formed schema honors.
# ---------------------------------------------------------------------------

SCALAR_TYPES = ["string", "integer", "number", "boolean"]
ALL_TYPES = SCALAR_TYPES + ["array", "object"]

# Field / parameter names: short, non-empty identifiers so name collisions are
# rare and dict keys stay hashable strings.
IDENTIFIERS = st.text(alphabet="abcdefghijklmnopqrstuvwxyz_", min_size=1, max_size=6)


def _value_strategy(declared_type):
    """A Hypothesis strategy producing a value of the given declared type."""
    if declared_type == "string":
        return st.text(min_size=0, max_size=8)
    if declared_type == "integer":
        return st.integers(min_value=-1000, max_value=1000)
    if declared_type == "number":
        return st.floats(allow_nan=False, allow_infinity=False, width=32)
    if declared_type == "boolean":
        return st.booleans()
    if declared_type == "array":
        return st.lists(st.integers(min_value=-100, max_value=100), max_size=3)
    if declared_type == "object":
        return st.dictionaries(IDENTIFIERS, st.integers(), max_size=3)
    raise AssertionError(f"unhandled type {declared_type!r}")


def _matches_declared_type(value, declared_type):
    """Runtime-type check for a value against its declared JSON Schema type.

    ``bool`` is a subclass of ``int`` in Python, so ``integer``/``number`` checks
    explicitly exclude booleans to keep the type mapping faithful.
    """
    if declared_type == "string":
        return isinstance(value, str)
    if declared_type == "integer":
        return isinstance(value, int) and not isinstance(value, bool)
    if declared_type == "number":
        return isinstance(value, (int, float)) and not isinstance(value, bool)
    if declared_type == "boolean":
        return isinstance(value, bool)
    if declared_type == "array":
        return isinstance(value, list)
    if declared_type == "object":
        return isinstance(value, dict)
    return False


# ---------------------------------------------------------------------------
# Generators for schema property nodes, request body schemas, and parameters.
# Each field/parameter carries at most one decoration (enum XOR example XOR
# examples) so the builder's example-over-enum-over-canonical precedence is
# exercised cleanly and the expected value is unambiguous.
# ---------------------------------------------------------------------------


@st.composite
def _property_node(draw):
    """A single JSON Schema property node: a declared ``type`` plus an optional
    ``enum``/``example``/``examples`` decoration (all type-consistent)."""
    declared_type = draw(st.sampled_from(ALL_TYPES))
    node = {"type": declared_type}

    decoration = draw(st.sampled_from(["plain", "enum", "example", "examples"]))
    if decoration == "enum" and declared_type in SCALAR_TYPES:
        node["enum"] = draw(
            st.lists(_value_strategy(declared_type), min_size=1, max_size=4, unique_by=repr)
        )
    elif decoration == "example":
        node["example"] = draw(_value_strategy(declared_type))
    elif decoration == "examples":
        node["examples"] = draw(
            st.lists(_value_strategy(declared_type), min_size=1, max_size=3)
        )
    return node


@st.composite
def _body_schema(draw):
    """An object request-body schema with a mix of required/optional fields."""
    names = draw(st.lists(IDENTIFIERS, min_size=0, max_size=5, unique=True))
    properties = {}
    required = []
    for name in names:
        properties[name] = draw(_property_node())
        if draw(st.booleans()):
            required.append(name)

    schema = {"type": "object", "properties": properties}
    if required:
        schema["required"] = required
    return schema


@st.composite
def _spec_parameter(draw):
    """A SpecParameter in query/header/path location with an optional decoration.

    SpecParameter carries no nested ``items`` schema, so an ``array`` parameter
    yields a single canonical string item from the builder; the top-level runtime
    type (``list``) is what the property asserts.
    """
    declared_type = draw(st.sampled_from(ALL_TYPES))
    location = draw(st.sampled_from(["query", "header", "path"]))
    required = draw(st.booleans())

    enum = None
    example = None
    examples = None
    decoration = draw(st.sampled_from(["plain", "enum", "example", "examples"]))
    if decoration == "enum" and declared_type in SCALAR_TYPES:
        enum = draw(
            st.lists(_value_strategy(declared_type), min_size=1, max_size=4, unique_by=repr)
        )
    elif decoration == "example":
        example = draw(_value_strategy(declared_type))
    elif decoration == "examples":
        examples = draw(st.lists(_value_strategy(declared_type), min_size=1, max_size=3))

    return SpecParameter(
        name=draw(IDENTIFIERS),
        location=location,
        type=declared_type,
        required=required,
        enum=enum,
        example=example,
        examples=examples,
    )


@st.composite
def _spec_operation(draw):
    """A SpecOperation with a typed request body and unique-named parameters."""
    schema = draw(_body_schema())
    parameters = draw(
        st.lists(_spec_parameter(), max_size=5, unique_by=lambda p: p.name)
    )
    return SpecOperation(
        path="/resource/{id}",
        method="POST",
        parameters=parameters,
        request_body_schema=schema,
        security=[],
    )


def _assert_value_valid(value, declared_type, enum, example, examples):
    """Assert a built value honors type, enum, and example constraints."""
    # Type: the runtime type always matches the declared JSON Schema type.
    assert _matches_declared_type(value, declared_type), (
        f"value {value!r} does not match declared type {declared_type!r}"
    )

    # Precedence mirrors the builder: example/examples first, then enum.
    if example is not None:
        assert value == example, f"expected declared example {example!r}, got {value!r}"
    elif examples:
        assert value == examples[0], (
            f"expected first declared examples entry {examples[0]!r}, got {value!r}"
        )
    elif enum:
        assert value in enum, f"value {value!r} not drawn from declared enum {enum!r}"


# ---------------------------------------------------------------------------
# Property 30
# ---------------------------------------------------------------------------


@settings(max_examples=150)
@given(operation=_spec_operation())
def test_typed_payload_honors_types_required_and_enums(operation):
    """A built Typed_Payload and parameter set honor declared types, required
    fields, enums, and examples for every SpecOperation.

    **Validates: Requirements 57.3, 52.1, 52.2, 52.3**
    """
    schema = operation.request_body_schema
    properties = schema.get("properties") or {}
    required = schema.get("required") or []

    body = build_typed_payload(operation)

    # Every declared required field is present in the built body (Req 52.1).
    for name in required:
        assert name in body, f"required field {name!r} missing from body"

    # Every built field's value honors its declared type/enum/example (Reqs
    # 52.1-52.3).
    for name, value in body.items():
        node = properties.get(name, {})
        _assert_value_valid(
            value,
            node.get("type", "string"),
            node.get("enum"),
            node.get("example"),
            node.get("examples"),
        )

    # Parameter values honor the same contract, grouped by query/header; path
    # parameters are intentionally excluded from the output.
    grouped = build_typed_params(operation)
    assert set(grouped) == {"query", "header"}

    for param in operation.parameters:
        if param.location == "path":
            assert param.name not in grouped["query"]
            assert param.name not in grouped["header"]
            continue

        assert param.name in grouped[param.location], (
            f"{param.location} parameter {param.name!r} missing from built params"
        )
        _assert_value_valid(
            grouped[param.location][param.name],
            param.type,
            param.enum,
            param.example,
            param.examples,
        )


if __name__ == "__main__":
    pytest.main([__file__, "-q"])
