"""
Replay command — re-issue HTTP requests captured in prior scan reports.

Extracted from ``apileaks.py`` (monolith decomposition, Phase 5).
"""

from __future__ import annotations

import asyncio
import sys

import click

from cli.output import print_banner
from cli.parsers import (
    parse_header_options,
    validate_header_options,
)


@click.command(name="replay")
@click.argument("report", type=click.Path(exists=True, readable=True))
@click.option(
    "--url",
    "-u",
    "url_filter",
    default=None,
    help="Filter: only replay requests whose URL contains this substring.",
)
@click.option(
    "--method",
    "-m",
    "method_filter",
    default=None,
    help="Filter: only replay requests with this HTTP method (e.g. POST).",
)
@click.option(
    "--source",
    "source_filter",
    type=click.Choice(["endpoint", "finding"], case_sensitive=False),
    default=None,
    help="Filter: only replay items from 'endpoint' or 'finding' sections.",
)
@click.option(
    "--index",
    "-i",
    "index",
    type=int,
    default=None,
    help="Replay only the item at this index in the filtered list (0-based).",
)
@click.option(
    "--list",
    "-l",
    "list_only",
    is_flag=True,
    default=False,
    help="List all replayable requests from the report without replaying.",
)
@click.option(
    "--proxy",
    "proxy",
    default=None,
    metavar="URL",
    help="Forward the replayed request through an intercepting proxy "
    "(e.g. http://127.0.0.1:8080 for Burp/Caido).",
)
@click.option(
    "--jwt",
    "jwt_token",
    default=None,
    metavar="TOKEN",
    help="Bearer token to inject into the Authorization header.",
)
@click.option(
    "--header",
    "-H",
    "header",
    multiple=True,
    metavar="Name: Value",
    help="Additional request header (repeatable, e.g. -H 'X-API-Key: abc').",
)
@click.option(
    "--timeout",
    "timeout",
    type=float,
    default=30.0,
    show_default=True,
    help="Per-request timeout in seconds.",
)
@click.option(
    "--no-verify",
    "no_verify",
    is_flag=True,
    default=False,
    help="Disable TLS certificate verification.",
)
@click.option(
    "--all",
    "replay_all",
    is_flag=True,
    default=False,
    help="Replay ALL matching requests (default: only the first match).",
)
@click.pass_context
def replay_cmd(
    ctx,
    report,
    url_filter,
    method_filter,
    source_filter,
    index,
    list_only,
    proxy,
    jwt_token,
    header,
    timeout,
    no_verify,
    replay_all,
):
    """Replay HTTP requests from a prior apileaks scan report.

    REPORT is the path to a JSON report file generated by the ``dir``,
    ``par``, or ``scan`` commands.

    \b
    Examples:
      # List all replayable requests in a report
      apileaks replay reports/scan.json --list

      # Replay all POST findings through Burp
      apileaks replay reports/scan.json --source finding --method POST --proxy http://127.0.0.1:8080 --all

      # Replay item #3 from the list with a JWT
      apileaks replay reports/scan.json --index 3 --jwt eyJ...

      # Replay every endpoint containing '/admin'
      apileaks replay reports/scan.json --url /admin --all
    """

    from utils.replay import (
        _extract_requests_from_report,
        filter_requests,
        load_report,
        print_request_list,
        replay_request,
    )

    no_banner = ctx.obj.get("no_banner", False) if ctx.obj else False
    if not no_banner:
        print_banner()

    # Load report
    rep = load_report(report)
    all_requests = _extract_requests_from_report(rep)

    if not all_requests:
        click.echo("No replayable requests found in this report.", err=True)
        sys.exit(1)

    # Apply filters
    filtered = filter_requests(
        all_requests,
        url_filter=url_filter,
        method_filter=method_filter,
        source_filter=source_filter,
        index=index,
    )

    if not filtered:
        click.echo(
            "No requests matched the supplied filters. Use --list to see what is available.",
            err=True,
        )
        sys.exit(1)

    # List mode: just print the table and exit
    if list_only:
        print_request_list(filtered)
        return

    # If not --all, replay only the first match (unless --index was supplied)
    targets = filtered if replay_all else [filtered[0]]

    if len(targets) > 1:
        click.echo(
            f"Replaying {len(targets)} request(s)…  "
            f"(pass --index N to target a specific one, or --list to browse)"
        )

    # Parse extra headers
    extra_headers = parse_header_options(header)
    validate_header_options(header)

    # Run replays
    for entry in targets:
        try:
            asyncio.run(
                replay_request(
                    entry,
                    extra_headers=extra_headers or None,
                    jwt_token=jwt_token,
                    proxy=proxy,
                    verify_ssl=not no_verify,
                    timeout=timeout,
                    verbose=True,
                )
            )
        except Exception as exc:
            click.echo(f"Replay failed for {entry['method']} {entry['url']}: {exc}", err=True)
